### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by chandanankush** [VishwasKumar/IPLSentimentAlalysis#1]
Hi Vishwas,

terminal is throwing error while executing run command..

Traceback (most recent call last):
  File "get_tweets.py", line 2, in <module>
    from tweepy.streaming import StreamListener
ImportError: No module named tweepy.streaming

i am seeing that you are using Exporter.py an existing twitter fetch python script, so after fetching tweets are you going to process with +ve and -ve words in the tweets or else you will use NLTK ?

**Comment by VishwasKumar** [comment]
So it seems like you have not installed the tweepy library and hence you are getting that error.

About the sentiment analysis. It is ideal to use NTLK.
